export const businessTypes = [
  'Padaria',
  'Escritório de Advocacia',
  'Ateliê',
  'Mercado',
  'Restaurante',
  'Loja de Varejo',
  'Consultoria',
  'Academia',
  'Estúdio de Fotografia',
  'Galeria de Arte',
  'Consultório Odontológico',
  'Imobiliária',
  'Salão de Beleza',
  'Cafeteria',
  'Estúdio de Yoga',
  'Design de Interiores',
  'Escritório de Arquitetura',
  'Escola de Música',
  'Pet Shop',
  'Livraria',
  'Floricultura',
  'Assessoria de Casamentos',
  'Concessionária',
  'Agência de Viagens',
  'Outro'
];